### ISSUE TITLE
Wheldon, Kirk, and Finlay

### ISSUE THREAD

**Issue by OVGULIU** [SciML/DiffEqBenchmarks.jl#33]
HI all,

some bugs from benchmark test (Wheldon, Kirk, and Finlay)

UndefVarError: prob_dde_wheldon not defined

syntax: invalid syntax "1./"; add space(s) to clarify

best

**Comment by ChrisRackauckas** [comment]
Yeah many of these need a v1.0 update. They were last ran on v0.6. Two things show up there. First of all, broadcast rules changed in v1.0. But secondly, we made the problem library loading explicit, so the header should be:

https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/test/common.jl

**Comment by ChrisRackauckas** [comment]
I'm restructuring this whole repo to work on Weave files instead of notebooks, and will update it to v1.0 at the same time. PR: https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl/pull/32

**Comment by OVGULIU** [comment]
Perhaps, also the same question, which tutorial test input files are useful (v1.0 update) now.

**Comment by ChrisRackauckas** [comment]
The tutorial notebooks should all be unchanged from v0.6 to v1.0 since they didn't use our testing library which is what changed here. Other than small v0.6 vs v1.0 syntax differences of course. I plan to update all of these to the new Weave.jl format before February.

**Comment by ChrisRackauckas** [comment]
The update process is underway. The tutorial repo finished, and now they are all being updated 1 by 1 and run on a new server in https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl/pull/32 .
