### ISSUE TITLE
Pleiades 

### ISSUE THREAD

**Issue by mikelehu** [SciML/DiffEqBenchmarks.jl#95]
Ode function has an error:

This code is wrong,   
  for i in 14:28
     du[i] = zero(u[1])
  end

It would be
  for i in 15:28
    du[i] = zero(u[1])
  end

Regards,

**Comment by ChrisRackauckas** [comment]
Good catch. Thanks! Fixed in https://github.com/SciML/DiffEqBenchmarks.jl/commit/54d390aacc410c5c469bf6e67222f8fb8fad4724 . 

BTW, let me know what a good benchmark is to showcase your method in a good light and I'll add it in there.
